---
apiVersion: v1
kind: Pod
metadata:
  name: pod-template
  namespace: airflow-on-k8s
  labels:
    app: airflow
spec:
  initContainers:
    - name: git-sync
      image: "lostlakkris/git-sync"
      env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/danny-andersen/stock-picker.git"
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_ROOT
          value: "/git"
        - name: GIT_SYNC_ADD_USER
          value: "true"
        - name: GIT_SYNC_MAX_SYNC_FAILURES
          value: "1"
      volumeMounts:
        - name: airflow-dags
          mountPath: /git
  containers:
    - args: []
      command: []
      envFrom:
      - configMapRef: 
          name: airflow-postgres-configuration
      - configMapRef: 
          name: airflow-config
      - configMapRef: 
          name: stockpicker-config
      env:
      - name: AIRFLOW__CORE__EXECUTOR
        value: LocalExecutor      
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-airflow-secret
            key: postgresql-password
      - name: HDFS_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: hdfs-user-secret
            key: hdfs-user-password
image: dummy
      imagePullPolicy: IfNotPresent
      name: base
      ports: []
      volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
        - name: airflow-webserver-logs-claim
          mountPath: /opt/airflow/logs
        - name: stockpicker-libs-pvc
          mountPath: /data/lib
  hostNetwork: false
  restartPolicy: Never
  # securityContext:
  #   runAsUser: 50000
  serviceAccountName: airflow
  nodeSelector:
    {}
  affinity:
    {}
  tolerations:
    []
  volumes:
    - name: webserver-config
      secret:
        secretName: airflow-webserver-config
        defaultMode: 0644
    - name: airflow-dags
      emptyDir: {}
    - name: airflow-webserver-logs-claim
      persistentVolumeClaim:
        claimName: logs-pvc
    - name: stockpicker-libs-claim
      persistentVolumeClaim:
        claimName: stockpicker-libs-pvc


